config/routes.rb
Rails.application.routes.draw do
  resources :tiles
  resources :maps
  root to: 'game#menu'

  get '/map', to: 'game#map'

  get '/encounter', to: 'game#encounter'

  resources :familiars
  resources :moves
  resources :base_familiars
  resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/familiar.rb
class Familiar < ApplicationRecord
  belongs_to :player
  belongs_to :base_familiar
  
  enum status: { fainted: 0, inactive: 1, active: 2 }
  
  def nick_and_name
    "#{self.nickname} (#{self.base_familiar.name})"
  end
end

app/controllers/familiars_controller.rb
class FamiliarsController < ApplicationController
  before_action :set_familiar, only: [:show, :edit, :update, :destroy]

  # GET /familiars
  # GET /familiars.json
  def index
    @familiars = Familiar.all
  end

  # GET /familiars/1
  # GET /familiars/1.json
  def show
  end

  # GET /familiars/new
  def new
    @familiar = Familiar.new
  end

  # GET /familiars/1/edit
  def edit
  end

  # POST /familiars
  # POST /familiars.json
  def create
    @familiar = Familiar.new(familiar_params)

    respond_to do |format|
      if @familiar.save
        format.html { redirect_to @familiar, notice: 'Familiar was successfully created.' }
        format.json { render :show, status: :created, location: @familiar }
      else
        format.html { render :new }
        format.json { render json: @familiar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /familiars/1
  # PATCH/PUT /familiars/1.json
  def update
    respond_to do |format|
      if @familiar.update(familiar_params)
        format.html { redirect_to @familiar, notice: 'Familiar was successfully updated.' }
        format.json { render :show, status: :ok, location: @familiar }
      else
        format.html { render :edit }
        format.json { render json: @familiar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /familiars/1
  # DELETE /familiars/1.json
  def destroy
    @familiar.destroy
    respond_to do |format|
      format.html { redirect_to familiars_url, notice: 'Familiar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_familiar
      @familiar = Familiar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def familiar_params
      params.require(:familiar).permit(:nickname, :player_id, :base_familiar_id, :status, :health, :power)
    end
end

app/helpers/familiars_helper.rb
module FamiliarsHelper
end

app/views/familiars/_form.html.erb
<%= form_for(familiar) do |f| %>
  <% if familiar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(familiar.errors.count, "error") %> prohibited this familiar from being saved:</h2>

      <ul>
      <% familiar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </div>

  <div class="field">
    <%= f.label :player_id %>
    <%= f.select :player_id, Player.all.map { |player| [ player.name, player.id ] } %>
  </div>
  
  <div class="field">
    <%= f.label :base_familiar_id %>
    <%= f.select :base_familiar_id, BaseFamiliar.all.map { |familiar| [ familiar.name, familiar.id ] } %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.number_field :status %>
  </div>

  <div class="field">
    <%= f.label :health %>
    <%= f.number_field :health %>
  </div>

  <div class="field">
    <%= f.label :power %>
    <%= f.number_field :power %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/familiars/edit.html.erb
<h1>Editing Familiar</h1>

<%= render 'form', familiar: @familiar %>

<%= link_to 'Show', @familiar %> |
<%= link_to 'Back', familiars_path %>

app/views/familiars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Familiars</h1>

<table>
  <thead>
    <tr>
      <th>Nickname</th>
      <th>Player</th>
      <th>Base familiar</th>
      <th>Status</th>
      <th>Health</th>
      <th>Power</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @familiars.each do |familiar| %>
      <tr>
        <td><%= familiar.nickname %></td>
        <td><%= familiar.player.name %></td>
        <td><%= familiar.base_familiar.name %></td>
        <td><%= familiar.status %></td>
        <td><%= familiar.health %></td>
        <td><%= familiar.power %></td>
        <td><%= link_to 'Show', familiar %></td>
        <td><%= link_to 'Edit', edit_familiar_path(familiar) %></td>
        <td><%= link_to 'Destroy', familiar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Familiar', new_familiar_path %>

app/views/familiars/new.html.erb
<h1>New Familiar</h1>

<%= render 'form', familiar: @familiar %>

<%= link_to 'Back', familiars_path %>

app/views/familiars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @familiar.nickname %>
</p>

<p>
  <strong>Player:</strong>
  <%= @familiar.player.name %>
</p>

<p>
  <strong>Base familiar:</strong>
  <%= @familiar.base_familiar.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @familiar.status %>
</p>

<p>
  <strong>Health:</strong>
  <%= @familiar.health %>
</p>

<p>
  <strong>Power:</strong>
  <%= @familiar.power %>
</p>

<%= link_to 'Edit', edit_familiar_path(@familiar) %> |
<%= link_to 'Back', familiars_path %>