config/routes.rb
Rails.application.routes.draw do
  resources :tiles
  resources :maps
  root to: 'game#menu'

  get '/map', to: 'game#map'

  get '/encounter', to: 'game#encounter'

  resources :familiars
  resources :moves
  resources :base_familiars
  resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/move.rb
class Move < ApplicationRecord
  include HasElement
  has_and_belongs_to_many :base_familiars
  
  def name_and_element
    "#{self.name} (#{self.element})"
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]

  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to @move, notice: 'Move was successfully created.' }
        format.json { render :show, status: :created, location: @move }
      else
        format.html { render :new }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1
  # PATCH/PUT /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to @move, notice: 'Move was successfully updated.' }
        format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url, notice: 'Move was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def move_params
      params.require(:move).permit(:name, :element, :damage, :cost)
    end
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.erb
<%= form_for(move) do |f| %>
  <% if move.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(move.errors.count, "error") %> prohibited this move from being saved:</h2>

      <ul>
      <% move.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :element %>
    <%= f.select :element, Move.elements.keys.map { |element| [ element, element ] } %>
  </div>

  <div class="field">
    <%= f.label :damage %>
    <%= f.number_field :damage %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.number_field :cost %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moves/edit.html.erb
<h1>Editing Move</h1>

<%= render 'form', move: @move %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Element</th>
      <th>Damage</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr>
        <td><%= move.name %></td>
        <td><%= move.element %></td>
        <td><%= move.damage %></td>
        <td><%= move.cost %></td>
        <td><%= link_to 'Show', move %></td>
        <td><%= link_to 'Edit', edit_move_path(move) %></td>
        <td><%= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Move', new_move_path %>

app/views/moves/new.html.erb
<h1>New Move</h1>

<%= render 'form', move: @move %>

<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @move.name %>
</p>

<p>
  <strong>Element:</strong>
  <%= @move.element %>
</p>

<p>
  <strong>Damage:</strong>
  <%= @move.damage %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @move.cost %>
</p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>