config/routes.rb
Rails.application.routes.draw do
  resources :tiles
  resources :maps
  root to: 'game#menu'

  get '/map', to: 'game#map'

  get '/encounter', to: 'game#encounter'

  resources :familiars
  resources :moves
  resources :base_familiars
  resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/base_familiar.rb
class BaseFamiliar < ApplicationRecord
  include HasElement
  has_and_belongs_to_many :moves
end

app/controllers/base_familiars_controller.rb
class BaseFamiliarsController < ApplicationController
  before_action :set_base_familiar, only: [:show, :edit, :update, :destroy]

  # GET /base_familiars
  # GET /base_familiars.json
  def index
    @base_familiars = BaseFamiliar.all
  end

  # GET /base_familiars/1
  # GET /base_familiars/1.json
  def show
  end

  # GET /base_familiars/new
  def new
    @base_familiar = BaseFamiliar.new
  end

  # GET /base_familiars/1/edit
  def edit
  end

  # POST /base_familiars
  # POST /base_familiars.json
  def create
    @base_familiar = BaseFamiliar.new(base_familiar_params)

    respond_to do |format|
      if @base_familiar.save
        format.html { redirect_to @base_familiar, notice: 'Base familiar was successfully created.' }
        format.json { render :show, status: :created, location: @base_familiar }
      else
        format.html { render :new }
        format.json { render json: @base_familiar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /base_familiars/1
  # PATCH/PUT /base_familiars/1.json
  def update
    respond_to do |format|
      if @base_familiar.update(base_familiar_params)
        format.html { redirect_to @base_familiar, notice: 'Base familiar was successfully updated.' }
        format.json { render :show, status: :ok, location: @base_familiar }
      else
        format.html { render :edit }
        format.json { render json: @base_familiar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /base_familiars/1
  # DELETE /base_familiars/1.json
  def destroy
    @base_familiar.destroy
    respond_to do |format|
      format.html { redirect_to base_familiars_url, notice: 'Base familiar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_base_familiar
      @base_familiar = BaseFamiliar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def base_familiar_params
      params.require(:base_familiar).permit(:name, :health, :power, :element, :background, :move_ids => [])
    end
end

app/helpers/base_familiars_helper.rb
module BaseFamiliarsHelper
end

app/views/base_familiars/_form.html.erb
<%= form_for(base_familiar) do |f| %>
  <% if base_familiar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(base_familiar.errors.count, "error") %> prohibited this base_familiar from being saved:</h2>

      <ul>
      <% base_familiar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :health %>
    <%= f.number_field :health %>
  </div>

  <div class="field">
    <%= f.label :power %>
    <%= f.number_field :power %>
  </div>

  <div class="field">
    <%= f.label :element %>
    <%= f.select :element, BaseFamiliar.elements.keys.map { |element| [ element, element ] } %>
  </div>

  <div class="field">
    <%= f.label :background %>
    <%= f.text_field :background %>
  </div>
  
  <div class="field">
    <%= f.label :moves %>
    <%= f.select :move_ids, Move.all.map { |move| [ move.name_and_element, move.id ] }, {}, :multiple => true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/base_familiars/edit.html.erb
<h1>Editing Base Familiar</h1>

<%= render 'form', base_familiar: @base_familiar %>

<%= link_to 'Show', @base_familiar %> |
<%= link_to 'Back', base_familiars_path %>

app/views/base_familiars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Base Familiars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Health</th>
      <th>Power</th>
      <th>Element</th>
      <th>Background</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @base_familiars.each do |base_familiar| %>
      <tr>
        <td><%= base_familiar.name %></td>
        <td><%= base_familiar.health %></td>
        <td><%= base_familiar.power %></td>
        <td><%= base_familiar.element %></td>
        <td><%= base_familiar.background %></td>
        <td><%= link_to 'Show', base_familiar %></td>
        <td><%= link_to 'Edit', edit_base_familiar_path(base_familiar) %></td>
        <td><%= link_to 'Destroy', base_familiar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Base Familiar', new_base_familiar_path %>

app/views/base_familiars/new.html.erb
<h1>New Base Familiar</h1>

<%= render 'form', base_familiar: @base_familiar %>

<%= link_to 'Back', base_familiars_path %>

app/views/base_familiars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @base_familiar.name %>
</p>

<p>
  <strong>Health:</strong>
  <%= @base_familiar.health %>
</p>

<p>
  <strong>Power:</strong>
  <%= @base_familiar.power %>
</p>

<p>
  <strong>Element:</strong>
  <%= @base_familiar.element %>
</p>

<p>
  <strong>Background:</strong>
  <%= @base_familiar.background %>
</p>

<div>
<strong>Moves:</strong>
<ul>
  <% @base_familiar.moves.each do |move| %>
    <li>
      <%= move.name_and_element %>
    </li>
  <% end %>
</ul>
</div>
<%= link_to 'Edit', edit_base_familiar_path(@base_familiar) %> |
<%= link_to 'Back', base_familiars_path %>