config/routes.rb
Rails.application.routes.draw do
  resources :tiles
  resources :maps
  root to: 'game#menu'

  get '/map', to: 'game#map'

  get '/encounter', to: 'game#encounter'

  resources :familiars
  resources :moves
  resources :base_familiars
  resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
  enum gender: { male: 0, female: 1 }
  has_many :familiars
  belongs_to :map
  validates_presence_of :name

  after_initialize :set_defaults, unless: :persisted?

  after_commit do
    MapBroadcastJob.perform_later map
  end

  def self.at(x, y)
    where(x_pos: x, y_pos: y)
  end

  def move direction
    case direction
    when :up
      update y_pos: y_pos - 1 if map.passable?(x_pos, y_pos - 1)
    when :down
      update y_pos: y_pos + 1 if map.passable?(x_pos, y_pos + 1)
    when :left
      update x_pos: x_pos - 1 if map.passable?(x_pos, x_pos - 1)
    when :right
      update x_pos: x_pos + 1 if map.passable?(x_pos, x_pos + 1)
    end
  end

  private
    def set_defaults
      self.x_pos ||= 0
      self.y_pos ||= 0
      self.background ||= 'white'
      self.map ||= Map.first
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :gender, :x_pos, :y_pos, :background)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(player) do |f| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.select :gender, Player.genders.keys.map { |gender| [ gender, gender ] } %>
  </div>

  <div class="field">
    <%= f.label :x_pos %>
    <%= f.number_field :x_pos %>
  </div>

  <div class="field">
    <%= f.label :y_pos %>
    <%= f.number_field :y_pos %>
  </div>

  <div class="field">
    <%= f.label :background %>
    <%= f.color_field :background %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>X pos</th>
      <th>Y pos</th>
      <th>Background</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.gender %></td>
        <td><%= player.x_pos %></td>
        <td><%= player.y_pos %></td>
        <td><%= color_swatch player.background %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @player.gender %>
</p>

<p>
  <strong>X pos:</strong>
  <%= @player.x_pos %>
</p>

<p>
  <strong>Y pos:</strong>
  <%= @player.y_pos %>
</p>

<p>
  <strong>Background:</strong>
  <%= color_swatch @player.background %>
</p>

<div>
<strong>Familiar:</strong>
<ul>
  <% @player.familiars.each do |familiar| %>
    <li>
      <%= familiar.nick_and_name %>
    </li>
  <% end %>
</ul>
</div>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>